### ISSUE TITLE
编译报错了

### ISSUE THREAD

**Issue by wander555** [stark666/smzdm_bot#19]
![image](https://user-images.githubusercontent.com/6134211/108653231-e48fa100-7500-11eb-81e5-e75d536c0f2b.png)

**Comment by uyaboy** [comment]
碰上同样的问题，请帮忙解答一下如何解决，谢谢

**Comment by bafangseo** [comment]
Run python main.py
Traceback (most recent call last):
  File "main.py", line 57, in <module>
    res = sb.checkin()
  File "main.py", line 44, in checkin
    msg = self.session.get(url)
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/urllib3/connectionpool.py", line 706, in urlopen
    chunked=chunked,
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/urllib3/connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/urllib3/connection.py", line 234, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/http/client.py", line 1277, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/http/client.py", line 1318, in _send_request
    self.putheader(hdr, value)
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/urllib3/connection.py", line 219, in putheader
    _HTTPConnection.putheader(self, header, *values)
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/http/client.py", line 1250, in putheader
    values[i] = one_value.encode('latin-1')
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 668-673: ordinal not in range(256)
Error: Process completed with exit code 1

+1

**Comment by PRSJMC** [comment]
同样的问题
